### ISSUE TITLE
Simple way to start on bootup

### ISSUE THREAD

**Issue by 1000thSummer** [sophice/ahk-hide-volume-osd#1]
Found this charming script and like it.

There is a way to run the script automatically when windows boot up by adding a `scheduled task` on **user log on**.

The action is like
```
  <Actions Context="Author">
    <Exec>
      <Command>pathToAutoHotKeyFolder\AutoHotkeyU64.exe</Command>
      <Arguments>pathToGitRepo\ahk-hide-volume-osd-main\hide-volume-osd.ahk</Arguments>
    </Exec>
  </Actions>
```

**Comment by sophice** [comment]
Thanks for the feedback! Glad you like it!

I've been meaning to add this feature as I tend to always want it hidden. I'll give it a shot later tonight, along with the volume up/down PR you made!

**Comment by sophice** [comment]
I've just pushed a bunch of changes that fix issues with it running as a scheduled task on log in. I've also pushed an install.ahk and uninstall.ahk that create (and delete) the scheduled task for you. I've rebooted a couple times and it worked, so give it a shot. Let me know if you have any issues or suggestions to improve it further!

**Comment by 1000thSummer** [comment]
Thanks for the updates.
Your script worked just fine for me. Note that a 10 second delay for scheduled task works more stable for me.

I am now using the script by default and just uninstalled its ancestor lol.
